name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: checkboxes
    id: existing-feature
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists for the feature you are requesting.
      options:
      - label: I have searched the existing feature requests
        required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would be helpful)
        - High (needed for my use case)
        - Critical (blocking my use case)
      default: 1
    validations:
      required: true
  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Are you willing to contribute to this feature?
      description: Let us know if you'd be interested in implementing this feature yourself.
      options:
        - label: Yes, I'm willing to contribute
        - label: Yes, but I would need guidance
        - label: No, I'm not able to contribute at this time
